apiVersion : apps/v1
kind: Deployment
metadata:
  name: collinsctkazurewebapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collinsctkazurewebapp
  template:
    metadata:
      labels:
        app: collinsctkazurewebapp 
    spec:
      containers:
        - name: collinsctkazurewebapp 
          image: qytangcr.azurecr.io/collinsctkazurewebapp
          ports:
          - containerPort: 80